// File: src/Map.cpp (UPDATED - Full tilemap editor integration with collision)
#include "Map.hpp"
#include <algorithm>
#include <random>
#include <utility>
#include <cmath>
#include <iostream>
#include <fstream>
#include <sstream>

// Tile ID constants - CORRECTED with Angle/Angle2 at 34-35
enum EditorTileType : int
{
    EDITOR_NONE = 0,

    // BASE LAYER (1-14)
    EDITOR_FLOOR = 1,
    EDITOR_WALL_MID_TOP = 2,
    EDITOR_WALL_MID_BOTTOM = 3,
    EDITOR_CLASSWALL_TOP = 4,
    EDITOR_CLASSWALL_BOTTOM = 5,
    EDITOR_WALL_SEP_LEFT = 6,
    EDITOR_WALL_SEP_RIGHT = 7,
    EDITOR_WALL_SEP_BOTTOM = 8,

    EDITOR_CORNER_BR1 = 9,
    EDITOR_CORNER_BR2 = 10,
    EDITOR_CORNER_BL1 = 11,
    EDITOR_CORNER_BL2 = 12,
    EDITOR_CORNER_TL = 13,
    EDITOR_CORNER_TR = 14,

    // OVERLAY LAYER
    EDITOR_ENTRANCE = 15,
    EDITOR_DOOR_TOP = 16,
    EDITOR_DOOR_BOTTOM = 17,
    EDITOR_DOOR_OPEN_TOP = 18,
    EDITOR_DOOR_OPEN_BOTTOM = 19,
    EDITOR_CLOCK = 20,
    EDITOR_CHAIR = 21,
    EDITOR_DESK_TL = 22,
    EDITOR_DESK_TR = 23,
    EDITOR_DESK_BL = 24,
    EDITOR_DESK_BR = 25,
    EDITOR_PLANT_TOP = 26,
    EDITOR_PLANT_BOTTOM = 27,
    EDITOR_LOCKER_TOP = 28,
    EDITOR_LOCKER_BOTTOM = 29,
    EDITOR_BOOKSHELF_TL = 30,
    EDITOR_BOOKSHELF_TR = 31,
    EDITOR_BOOKSHELF_BL = 32,
    EDITOR_BOOKSHELF_BR = 33,

    // ⚠️ Angle/Angle2 inserted here, shifting everything after
    EDITOR_ANGLE = 34,
    EDITOR_ANGLE2 = 35,

    EDITOR_BOX = 36,          // Shifted from 34
    EDITOR_VENT = 37,         // Shifted from 35
    EDITOR_WATER_TOP = 38,    // Shifted from 36
    EDITOR_WATER_BOTTOM = 39, // Shifted from 37
    EDITOR_BOARD_TL = 40,     // Shifted from 38
    EDITOR_BOARD_TR = 41,     // Shifted from 39
    EDITOR_BOARD_BL = 42,     // Shifted from 40
    EDITOR_BOARD_BR = 43      // Shifted from 41
};

// Initialize static members
size_t Map::WIDTH = 32;
size_t Map::HEIGHT = 16;
float Map::TILE_SIZE = 64.0f;

void Map::initializeDimensions(unsigned int screenWidth, unsigned int screenHeight)
{
    const float TARGET_TILE_SIZE = 64.0f;
    WIDTH = static_cast<size_t>(screenWidth / TARGET_TILE_SIZE);
    HEIGHT = static_cast<size_t>(screenHeight / TARGET_TILE_SIZE);

    if (WIDTH < 20)
        WIDTH = 20;
    if (HEIGHT < 12)
        HEIGHT = 12;

    TILE_SIZE = static_cast<float>(screenWidth) / static_cast<float>(WIDTH);
    HEIGHT = static_cast<size_t>(screenHeight / TILE_SIZE);

    std::cout << "Map dimensions: " << WIDTH << "x" << HEIGHT
              << " tiles, tile size: " << TILE_SIZE << "px" << std::endl;
}

Map::Map(const MapConfig &config, b2World *physicsWorld)
    : config_(config), physicsWorld_(physicsWorld)
{
    grid_.resize(HEIGHT);
    for (auto &row : grid_)
    {
        row.resize(WIDTH);
    }

    // Load from CSV generated by tilemap editor
    if (!loadFromCSV("maps/map_1.csv"))
    {
        std::cerr << "Failed to load map from CSV, creating empty map" << std::endl;
        initializeGrid();
    }

    // Create physics colliders if physics world is available
    if (physicsWorld_)
    {
        createPhysicsColliders();
    }
}

bool Map::loadFromCSV(const std::string &filename)
{
    std::ifstream file(filename);
    if (!file.is_open())
    {
        std::cerr << "Could not open map file: " << filename << std::endl;
        return false;
    }

    std::string line;
    bool readingBase = false;
    bool readingOverlay = false;
    size_t row = 0;

    clearGrid();
    clearPhysicsBodies();

    std::cout << "Loading map from " << filename << "..." << std::endl;

    while (std::getline(file, line))
    {
        // Check for layer markers
        if (line == "BASE_LAYER")
        {
            readingBase = true;
            readingOverlay = false;
            row = 0;
            continue;
        }
        else if (line == "OVERLAY_LAYER")
        {
            readingBase = false;
            readingOverlay = true;
            row = 0;
            continue;
        }

        // Skip empty lines
        if (line.empty())
            continue;

        // Parse CSV line
        if ((readingBase || readingOverlay) && row < HEIGHT)
        {
            std::stringstream ss(line);
            std::string value;
            size_t col = 0;

            while (std::getline(ss, value, ',') && col < WIDTH)
            {
                try
                {
                    int tileId = std::stoi(value);

                    if (readingBase)
                    {
                        // Map tile IDs from editor to game tile states
                        grid_[row][col].state = mapEditorIdToTileState(tileId);

                        // Store wall type for walls
                        if (grid_[row][col].state == TileState::Wall)
                        {
                            grid_[row][col].wallType = mapEditorIdToWallType(tileId);
                        }

                        // Store original tile ID for debugging
                        grid_[row][col].editorTileId = tileId;
                    }
                    else if (readingOverlay)
                    {
                        // Handle overlay data (props, decorations)
                        if (tileId != 0) // 0 means empty
                        {
                            mapOverlayToDecoration(col, row, tileId);
                        }
                    }
                }
                catch (const std::exception &e)
                {
                    std::cerr << "Error parsing tile at (" << col << "," << row << "): " << e.what() << std::endl;
                }
                col++;
            }
            row++;
        }
    }

    file.close();

    // Apply auto-tiling to fix any wall connections
    applyAutoTiling();

    // Find safe spawn point (look for Entrance tile)
    findSafeSpawnPoint();

    // Convert some floors to flammable (grass)
    std::random_device rd;
    std::mt19937 gen(rd());
    convertFloorToFlammable(gen);

    std::cout << "✓ Map loaded successfully from " << filename << std::endl;
    std::cout << "  Grid size: " << WIDTH << "x" << HEIGHT << std::endl;
    std::cout << "  Safe spawn: (" << safeSpawnPoint_.x << ", " << safeSpawnPoint_.y << ")" << std::endl;

    markFurnitureAsFlammable();

    return true;
}

TileState Map::mapEditorIdToTileState(int editorId)
{
    switch (editorId)
    {
    case EDITOR_FLOOR:
        return TileState::Floor;

    // All wall types map to Wall state
    case EDITOR_WALL_MID_TOP:
    case EDITOR_WALL_MID_BOTTOM:
    case EDITOR_CLASSWALL_TOP:
    case EDITOR_CLASSWALL_BOTTOM:
    case EDITOR_WALL_SEP_LEFT:
    case EDITOR_WALL_SEP_RIGHT:
    case EDITOR_WALL_SEP_BOTTOM:
    case EDITOR_CORNER_BR1:
    case EDITOR_CORNER_BR2:
    case EDITOR_CORNER_BL1:
    case EDITOR_CORNER_BL2:
    case EDITOR_CORNER_TL:
    case EDITOR_CORNER_TR:
        return TileState::Wall;

    case EDITOR_NONE:
    default:
        return TileState::Empty; // Changed from Floor to Empty for void areas
    }
}

WallType Map::mapEditorIdToWallType(int editorId)
{
    switch (editorId)
    {
    case EDITOR_WALL_MID_TOP:
    case EDITOR_CLASSWALL_TOP:
        return WallType::Top;

    case EDITOR_WALL_MID_BOTTOM:
    case EDITOR_CLASSWALL_BOTTOM:
        return WallType::Bottom;

    case EDITOR_WALL_SEP_LEFT:
        return WallType::Left;

    case EDITOR_WALL_SEP_RIGHT:
        return WallType::Right;

    case EDITOR_CORNER_TL: // 13
        return WallType::TopLeft;

    case EDITOR_CORNER_TR: // 14
        return WallType::TopRight;

    case EDITOR_CORNER_BL1: // 11
    case EDITOR_CORNER_BL2: // 12
        return WallType::BottomLeft;

    case EDITOR_CORNER_BR1: // 9
    case EDITOR_CORNER_BR2: // 10
        return WallType::BottomRight;

    case EDITOR_WALL_SEP_BOTTOM:
        return WallType::Bottom;

    default:
        return WallType::Top;
    }
}

void Map::mapOverlayToDecoration(size_t x, size_t y, int overlayId)
{
    // Store the overlay ID for rendering
    grid_[y][x].overlayTileId = overlayId;

    switch (overlayId)
    {
    case EDITOR_ENTRANCE:
        // // Mark as spawn point - ALWAYS set this
        // safeSpawnPoint_ = gridToWorld(x, y);
        // std::cout << "  Found Entrance at (" << x << ", " << y << ")" << std::endl;
        // std::cout << "  Spawn point set to: (" << safeSpawnPoint_.x << ", " << safeSpawnPoint_.y << ")" << std::endl;
        // FIXED: Calculate spawn point in center of tile (world coordinates)
        safeSpawnPoint_ = sf::Vector2f(
            (x + 0.5f) * TILE_SIZE, // Center X of tile
            (y + 0.5f) * TILE_SIZE  // Center Y of tile
        );
        std::cout << "  Found Entrance at grid (" << x << ", " << y << ")" << std::endl;
        std::cout << "  Spawn point set to world: (" << safeSpawnPoint_.x << ", " << safeSpawnPoint_.y << ")" << std::endl;
        break;

    case EDITOR_CLOCK:
        grid_[y][x].hasClock = true;
        break;

    case EDITOR_DOOR_TOP:
    case EDITOR_DOOR_BOTTOM:
        grid_[y][x].isDoor = true;
        grid_[y][x].state = TileState::Door;
        break;

    // Desk parts (make them solid props)
    case EDITOR_DESK_TL:
    case EDITOR_DESK_TR:
    case EDITOR_DESK_BL:
    case EDITOR_DESK_BR:
        if (grid_[y][x].state == TileState::Floor ||
            grid_[y][x].state == TileState::Flammable)
        {
            grid_[y][x].state = TileState::Prop;
            grid_[y][x].propVariant = 3; // Desk variant
        }
        break;

    case EDITOR_CHAIR:
        if (grid_[y][x].state == TileState::Floor ||
            grid_[y][x].state == TileState::Flammable)
        {
            grid_[y][x].state = TileState::Prop;
            grid_[y][x].propVariant = 1; // Chair variant
        }
        break;

    case EDITOR_LOCKER_TOP:
    case EDITOR_LOCKER_BOTTOM:
        if (grid_[y][x].state == TileState::Floor ||
            grid_[y][x].state == TileState::Flammable)
        {
            grid_[y][x].state = TileState::Prop;
            grid_[y][x].propVariant = 0; // Locker variant
        }
        break;

    case EDITOR_BOOKSHELF_TL:
    case EDITOR_BOOKSHELF_TR:
    case EDITOR_BOOKSHELF_BL:
    case EDITOR_BOOKSHELF_BR:
        if (grid_[y][x].state == TileState::Floor ||
            grid_[y][x].state == TileState::Flammable)
        {
            grid_[y][x].state = TileState::Prop;
            grid_[y][x].propVariant = 4; // Bookshelf variant
        }
        break;

    case EDITOR_PLANT_TOP:
    case EDITOR_PLANT_BOTTOM:
        if (grid_[y][x].state == TileState::Floor ||
            grid_[y][x].state == TileState::Flammable)
        {
            grid_[y][x].state = TileState::Prop;
            grid_[y][x].propVariant = 2; // Plant variant
        }
        break;

    default:
        // Other overlays (box, vent, board, etc.) are just decorative
        // They don't block movement, just render on top
        break;
    }
}

void Map::clearGrid()
{
    for (size_t y = 0; y < HEIGHT; ++y)
    {
        for (size_t x = 0; x < WIDTH; ++x)
        {
            grid_[y][x].state = TileState::Floor;
            grid_[y][x].wallType = WallType::None;
            grid_[y][x].hasClock = false;
            grid_[y][x].isDoor = false;
            grid_[y][x].burnTime = 0.0f;
            grid_[y][x].heatAccumulated = 0.0f;
            grid_[y][x].propVariant = 0;
        }
    }
}

void Map::clearPhysicsBodies()
{
    if (physicsWorld_)
    {
        for (b2Body *body : wallBodies_)
        {
            if (body)
            {
                physicsWorld_->DestroyBody(body);
            }
        }
    }
    wallBodies_.clear();
}

void Map::initializeGrid()
{
    clearGrid();

    std::cout << "Creating default bordered map..." << std::endl;

    // Create walls around the border
    for (size_t x = 0; x < WIDTH; ++x)
    {
        grid_[0][x].state = TileState::Wall;
        grid_[HEIGHT - 1][x].state = TileState::Wall;
    }
    for (size_t y = 0; y < HEIGHT; ++y)
    {
        grid_[y][0].state = TileState::Wall;
        grid_[y][WIDTH - 1].state = TileState::Wall;
    }

    applyAutoTiling();
    findSafeSpawnPoint();

    std::random_device rd;
    std::mt19937 gen(rd());
    convertFloorToFlammable(gen);
}

void Map::findSafeSpawnPoint()
{
    // If spawn was set by Entrance tile, we're done
    if (safeSpawnPoint_.x != 0.0f || safeSpawnPoint_.y != 0.0f)
    {
        return;
    }

    // Find the first floor tile that's not near walls
    for (size_t y = 2; y < HEIGHT - 2; ++y)
    {
        for (size_t x = 2; x < WIDTH - 2; ++x)
        {
            if (grid_[y][x].state == TileState::Floor ||
                grid_[y][x].state == TileState::Flammable)
            {
                // Check if area is clear
                bool clear = true;
                for (int dy = -1; dy <= 1; ++dy)
                {
                    for (int dx = -1; dx <= 1; ++dx)
                    {
                        if (grid_[y + dy][x + dx].state == TileState::Wall)
                        {
                            clear = false;
                            break;
                        }
                    }
                    if (!clear)
                        break;
                }

                if (clear)
                {
                    // safeSpawnPoint_ = gridToWorld(x, y);
                    // return;
                    // FIXED: Use center of tile
                    safeSpawnPoint_ = sf::Vector2f(
                        (x + 0.5f) * TILE_SIZE,
                        (y + 0.5f) * TILE_SIZE);
                    std::cout << "  Fallback spawn at grid (" << x << ", " << y << ")" << std::endl;
                    std::cout << "  World position: (" << safeSpawnPoint_.x << ", " << safeSpawnPoint_.y << ")" << std::endl;
                    return;
                }
            }
        }
    }

    // // Fallback to center
    // safeSpawnPoint_ = sf::Vector2f(
    //     (WIDTH / 2) * TILE_SIZE,
    //     (HEIGHT / 2) * TILE_SIZE);
    // Fallback to center of map
    safeSpawnPoint_ = sf::Vector2f(
        (WIDTH / 2.0f + 0.5f) * TILE_SIZE,
        (HEIGHT / 2.0f + 0.5f) * TILE_SIZE);
    std::cout << "  Using map center as spawn" << std::endl;
}

void Map::applyAutoTiling()
{
    for (size_t y = 0; y < HEIGHT; ++y)
    {
        for (size_t x = 0; x < WIDTH; ++x)
        {
            if (grid_[y][x].state == TileState::Wall)
            {
                grid_[y][x].wallType = calculateWallType(x, y);
            }
        }
    }
}

WallType Map::calculateWallType(int x, int y) const
{
    bool up = isWall(x, y - 1);
    bool down = isWall(x, y + 1);
    bool left = isWall(x - 1, y);
    bool right = isWall(x + 1, y);

    // Four-way connection
    if (up && down && left && right)
        return WallType::Cross;

    // T-junctions
    if (up && down && left && !right)
        return WallType::TJunctionLeft;
    if (up && down && !left && right)
        return WallType::TJunctionRight;
    if (left && right && up && !down)
        return WallType::TJunctionTop;
    if (left && right && !up && down)
        return WallType::TJunctionBottom;

    // Corners
    if (right && down && !up && !left)
        return WallType::TopLeft;
    if (left && down && !up && !right)
        return WallType::TopRight;
    if (right && up && !down && !left)
        return WallType::BottomLeft;
    if (left && up && !down && !right)
        return WallType::BottomRight;

    // Straight walls
    if (left && right && !up && !down)
        return WallType::Horizontal;
    if (up && down && !left && !right)
        return WallType::Vertical;

    // End caps
    if (right && !left && !up && !down)
        return WallType::EndLeft;
    if (left && !right && !up && !down)
        return WallType::EndRight;
    if (down && !up && !left && !right)
        return WallType::EndTop;
    if (up && !down && !left && !right)
        return WallType::EndBottom;

    return WallType::Top;
}

bool Map::isWall(int x, int y) const
{
    if (x < 0 || x >= static_cast<int>(WIDTH) ||
        y < 0 || y >= static_cast<int>(HEIGHT))
        return false;

    return grid_[y][x].state == TileState::Wall;
}

void Map::convertFloorToFlammable(std::mt19937 &gen)
{
    std::uniform_real_distribution<float> dis(0.0f, 1.0f);

    for (size_t y = 0; y < HEIGHT; ++y)
    {
        for (size_t x = 0; x < WIDTH; ++x)
        {
            if (grid_[y][x].state == TileState::Floor)
            {
                if (dis(gen) < config_.flammableDensity)
                {
                    grid_[y][x].state = TileState::Flammable;
                    grid_[y][x].ignitionThreshold = 0.8f + dis(gen) * 0.4f;
                }
            }
        }
    }
}

void Map::createPhysicsColliders()
{
    if (!physicsWorld_)
        return;

    clearPhysicsBodies();

    std::cout << "Creating physics colliders..." << std::endl;

    for (size_t y = 0; y < HEIGHT; ++y)
    {
        for (size_t x = 0; x < WIDTH; ++x)
        {
            if (grid_[y][x].state == TileState::Wall)
            {
                createWallCollider(x, y);
            }
        }
    }
    createFurnitureColliders(physicsWorld_);
    std::cout << "✓ Created " << wallBodies_.size() << " wall colliders" << std::endl;
}

void Map::createWallCollider(int x, int y)
{
    b2BodyDef bodyDef;
    bodyDef.type = b2_staticBody;

    // Box2D position is the center of the body
    float centerX = (x + 0.5f) * TILE_SIZE;
    float centerY = (y + 0.5f) * TILE_SIZE;

    // Convert to Box2D units (30 pixels = 1 meter)
    bodyDef.position.Set(centerX / 30.0f, centerY / 30.0f);

    b2Body *body = physicsWorld_->CreateBody(&bodyDef);

    b2PolygonShape shape;
    float halfSize = (TILE_SIZE / 2.0f) / 30.0f;
    shape.SetAsBox(halfSize, halfSize);

    b2FixtureDef fixtureDef;
    fixtureDef.shape = &shape;
    fixtureDef.density = 1.0f;
    fixtureDef.friction = 0.3f;

    body->CreateFixture(&fixtureDef);

    wallBodies_.push_back(body);
}

// Tile access methods
TileState Map::getTileState(size_t x, size_t y) const
{
    if (x >= WIDTH || y >= HEIGHT)
        return TileState::Wall;
    return grid_[y][x].state;
}

Tile &Map::getTile(size_t x, size_t y)
{
    return grid_[y][x];
}

const Tile &Map::getTile(size_t x, size_t y) const
{
    return grid_[y][x];
}

void Map::setTileState(size_t x, size_t y, TileState state)
{
    if (x < WIDTH && y < HEIGHT)
    {
        grid_[y][x].state = state;
    }
}

bool Map::isValidPosition(int x, int y) const
{
    return x >= 0 && x < static_cast<int>(WIDTH) &&
           y >= 0 && y < static_cast<int>(HEIGHT);
}

bool Map::isWalkable(int x, int y) const
{
    if (!isValidPosition(x, y))
        return false;
    TileState state = grid_[y][x].state;
    return state != TileState::Wall && state != TileState::Prop;
}

sf::FloatRect Map::getTileCollisionRect(int x, int y) const
{
    return sf::FloatRect(
        x * TILE_SIZE,
        y * TILE_SIZE,
        TILE_SIZE,
        TILE_SIZE);
}

bool Map::canPlaceBody(sf::FloatRect bodyRect) const
{
    int minX = static_cast<int>(bodyRect.left / TILE_SIZE);
    int maxX = static_cast<int>((bodyRect.left + bodyRect.width) / TILE_SIZE);
    int minY = static_cast<int>(bodyRect.top / TILE_SIZE);
    int maxY = static_cast<int>((bodyRect.top + bodyRect.height) / TILE_SIZE);

    for (int y = minY; y <= maxY; ++y)
    {
        for (int x = minX; x <= maxX; ++x)
        {
            if (!isWalkable(x, y))
                return false;
        }
    }
    return true;
}

std::pair<int, int> Map::worldToGrid(sf::Vector2f worldPos) const
{
    int gridX = static_cast<int>(worldPos.x / TILE_SIZE);
    int gridY = static_cast<int>(worldPos.y / TILE_SIZE);
    return {gridX, gridY};
}

sf::Vector2f Map::gridToWorld(size_t x, size_t y) const
{
    return sf::Vector2f(
        (x + 0.5f) * TILE_SIZE,
        (y + 0.5f) * TILE_SIZE);
}

sf::Vector2f Map::getSafeSpawnPoint() const
{
    return safeSpawnPoint_;
}

void Map::reset()
{
    // Reload from CSV
    if (!loadFromCSV("maps/map_1.csv"))
    {
        initializeGrid();
    }

    // Recreate physics colliders
    if (physicsWorld_)
    {
        createPhysicsColliders();
    }
}

bool Map::isSolid(int x, int y) const
{
    if (!isValidPosition(x, y))
        return true;
    return grid_[y][x].state == TileState::Wall;
}

// Add this to Map.cpp after loading from CSV
// This function should be called in loadFromCSV() after reading all tiles

void Map::markFurnitureAsFlammable()
{
    std::cout << "Marking furniture tiles as flammable..." << std::endl;
    int flammableCount = 0;

    for (size_t y = 0; y < HEIGHT; ++y)
    {
        for (size_t x = 0; x < WIDTH; ++x)
        {
            Tile &tile = grid_[y][x];

            // Check if this tile has flammable furniture in overlay
            bool isFurniture = (tile.overlayTileId == 21 || // Chair
                                tile.overlayTileId == 22 || // Desk TL
                                tile.overlayTileId == 23 || // Desk TR
                                tile.overlayTileId == 24 || // Desk BL
                                tile.overlayTileId == 25 || // Desk BR
                                tile.overlayTileId == 26 || // Plant Top
                                tile.overlayTileId == 27 || // Plant Bottom
                                tile.overlayTileId == 36);  // Box

            if (isFurniture)
            {
                // Make this tile flammable
                tile.state = TileState::Flammable;
                tile.ignitionThreshold = 0.8f; // How much heat needed to ignite
                tile.heatAccumulated = 0.0f;
                tile.burnTime = 0.0f;
                flammableCount++;
            }
            // If it's currently marked as flammable but NOT furniture, change it to floor
            else if (tile.state == TileState::Flammable)
            {
                tile.state = TileState::Floor;
            }
        }
    }

    std::cout << "  ✓ Marked " << flammableCount << " furniture tiles as flammable" << std::endl;
}

// IMPORTANT: Call this function at the END of loadFromCSV()
// Add this line right before the return true; statement in loadFromCSV():
//
//     markFurnitureAsFlammable();
//     return true;
// }

void Map::createFurnitureColliders(b2World *world)
{
    if (!world)
    {
        std::cerr << "Error: Physics world is null, cannot create furniture colliders" << std::endl;
        return;
    }

    std::cout << "Creating furniture colliders..." << std::endl;
    int colliderCount = 0;

    for (size_t y = 0; y < HEIGHT; ++y)
    {
        for (size_t x = 0; x < WIDTH; ++x)
        {
            Tile &tile = grid_[y][x];

            // Check if this tile has furniture
            bool isFurniture = (tile.overlayTileId == 21 || // Chair
                                tile.overlayTileId == 22 || // Desk TL
                                tile.overlayTileId == 23 || // Desk TR
                                tile.overlayTileId == 24 || // Desk BL
                                tile.overlayTileId == 25 || // Desk BR
                                tile.overlayTileId == 26 || // Plant Top
                                tile.overlayTileId == 27 || // Plant Bottom
                                tile.overlayTileId == 28 || // Locker Top
                                tile.overlayTileId == 29 || // Locker Bottom
                                tile.overlayTileId == 30 || // Bookshelf TL
                                tile.overlayTileId == 31 || // Bookshelf TR
                                tile.overlayTileId == 32 || // Bookshelf BL
                                tile.overlayTileId == 33 || // Bookshelf BR
                                tile.overlayTileId == 36);  // Box

            if (isFurniture)
            {
                // Calculate world position (center of tile)
                float worldX = (x + 0.5f) * TILE_SIZE;
                float worldY = (y + 0.5f) * TILE_SIZE;

                // Create body definition
                b2BodyDef bodyDef;
                bodyDef.type = b2_staticBody;
                bodyDef.position.Set(worldX, worldY);

                b2Body *body = world->CreateBody(&bodyDef);

                // Create box shape for furniture
                b2PolygonShape boxShape;

                // Different sizes for different furniture
                float halfWidth = TILE_SIZE * 0.5f;
                float halfHeight = TILE_SIZE * 0.5f;

                // Adjust collider size based on furniture type
                switch (tile.overlayTileId)
                {
                case 21: // Chair - smaller collider
                    halfWidth = TILE_SIZE * 0.35f;
                    halfHeight = TILE_SIZE * 0.35f;
                    break;
                case 22:
                case 23:
                case 24:
                case 25: // Desk - full size
                    halfWidth = TILE_SIZE * 0.48f;
                    halfHeight = TILE_SIZE * 0.48f;
                    break;
                case 26:
                case 27: // Plant - small collider
                    halfWidth = TILE_SIZE * 0.25f;
                    halfHeight = TILE_SIZE * 0.25f;
                    break;
                case 28:
                case 29: // Locker - full size
                case 30:
                case 31:
                case 32:
                case 33: // Bookshelf - full size
                    halfWidth = TILE_SIZE * 0.48f;
                    halfHeight = TILE_SIZE * 0.48f;
                    break;
                case 36: // Box - medium collider
                    halfWidth = TILE_SIZE * 0.4f;
                    halfHeight = TILE_SIZE * 0.4f;
                    break;
                default:
                    halfWidth = TILE_SIZE * 0.45f;
                    halfHeight = TILE_SIZE * 0.45f;
                    break;
                }

                boxShape.SetAsBox(halfWidth, halfHeight);

                // Create fixture
                b2FixtureDef fixtureDef;
                fixtureDef.shape = &boxShape;
                fixtureDef.density = 1.0f;
                fixtureDef.friction = 0.3f;

                body->CreateFixture(&fixtureDef);

                // Store body reference in tile (optional - for debugging)
                // tile.physicsBody = body;

                colliderCount++;
            }
        }
    }

    std::cout << "  ✓ Created " << colliderCount << " furniture colliders" << std::endl;
}

// IMPORTANT: This should be called in createPhysicsColliders()
// Add this call at the END of createPhysicsColliders(), after wall colliders are created:
//
// void Map::createPhysicsColliders(b2World* world) {
//     // ... existing wall collider code ...
//
//     // Add furniture colliders
//     createFurnitureColliders(world);
// }